const tarot = [
    {
        "nombre":"El Loco",
        "palo":"Arcanos Mayores",
        "valor":0,
        "rasgos_enderezada":"Despreocupación, Ideas originales, Decisiones importantes, Nuevos comienzos, Optimismo",
        "rasgos_girada":"Esfuerzo sin fruto, Caos, Falta de implicación, Accidentes e imprevistos, Malas decisiones",
        "pasado_enderezada":"Ser original y/o asumir riesgos te ha dado resultado antes. Una nueva forma de hacer te ha permitido crecer.",
        "pasado_girada":"La falta de organización o de implicación ya te ha costado tiempo y esfuerzo antes. Un mal juicio de la situación y/o un giro imprevisible te ha lastrado en el pasado.",
        "presente_enderezada":"Momento de cambios, pueden parecer lo que no son. Se necesita ponderar los riesgos y costes para tomar una buena decisión.",
        "presente_girada":"Esfuerzo que no lleva a ningún sitio, falta de concrección. Se necesita replanteamiento y revisión del entorno (planes y gentes).",
        "futuro_enderezada":"Necesidad de movimiento. Pensar de forma diferente, abandonar lo antiguo. Maneras nuevas de conseguir objetivos.",
        "futuro_girada":"Momento volátil. Imprevistos, peligro de equivocaciones, recibir malos consejos y engaños. Relaciones temporales, falta de compromiso.",
        "si_no_enderezada":"Optimismo, pueden venir decisiones importantes. Duda en positivo. Quizá sacar otra carta complementaría esta tirada.",
        "si_no_girada":"Inconsciencia, no está todo sobre la mesa. Duda y advertencia. Saca otra carta, pero ten presente esta.",
        "ordinal":0
    },
    {
        "nombre":"El Mago",
        "palo":"Arcanos Mayores",
        "valor":1,
        "rasgos_enderezada":"Seguridad, Creatividad, Comunicaciones importantes, Habilidad, Talento y competencia",
        "rasgos_girada":"Desconfianza · No saber lo que se quiere · Engaños · Incompetencia · Retrasos en los planes",
        "pasado_enderezada":"La confianza y la creatividad te ha dado resultado antes. La inteligencia y/o la habilidad te ha permitido crecer.",
        "pasado_girada":"Los engaños y que se retrasen tus objetivos han dejado huella antes. Te has fiado de la gente equivocada o que no tenía claras las cosas.",
        "presente_enderezada":"Se está dando un cambio o una nueva oportunidad. Para que el momento sea positivo necesitarás implicarte con tus mejores cualidades.",
        "presente_girada":"Lo que sea que estás intentando o haciendo se verá retrasado. Algo se está haciendo mal por falta de comunicación.",
        "futuro_enderezada":"Mucho a ganar y mucho a perder. Las amistades y relaciones que hayas cultivado influirán, pero debes hacer tu parte de la manera más competente posible.",
        "futuro_girada":"Estancamiento y retrasos. Algo o alguien obstaculiza tus avances. Te corresponderá a tí desbloquear la situación.",
        "si_no_enderezada":"Necesita tu acción y capacidad, SI.",
        "si_no_girada":"No solo depende de tí o de tus habilidades, NO.",     
        "ordinal":1   
    },
    {
        "nombre":"La Suma Sacerdotisa",
        "palo":"Arcanos Mayores",
        "valor":2,
        "rasgos_enderezada":"Feminidad · Estabilidad · Misterio · Comprensión y buen juicio · Intuición",
        "rasgos_girada":"Pasividad y desconexión · Celos · Desequilibrio · Mentiras de gente próxima · Planes ocultos",
        "pasado_enderezada":"Pasado monótono, has necesitado apoyo y compañia para abrirte a cosas e ideas nuevas. Esto puede seguir en el presente.",
        "pasado_girada":"Vienes de vivir en desequilibrio, con relaciones personales tormentosas y poca estabilidad laboral o de ingresos.",
        "presente_enderezada":"Pon el foco en tí. Es un momento personal y privado en el que reencontrarte con tu propio yo. Autoconocimiento. Mal momento para socializar o empezar relaciones.",
        "presente_girada":"Desafios invisibles, desconocidos o con datos aún no revelados. Es bueno fiarse de la intuición ahora.",
        "futuro_enderezada":"Se está en el buen camino, vienen recompensas. Se ha de perseverar. Disciplina y motivación serán nuestras herramientas.",
        "futuro_girada":"Tiempo inestable o de bloqueos. Problemas mal planteados o de los que no sabemos todo. Pasividad, pérdida de poder. Necesidad de reevaluar la situación y a nosotros mismos. Probablemente se necesitará ayuda de otros.",
        "si_no_enderezada":"Se necesita reflexión. Saca otra carta.",
        "si_no_girada":"Se necesita reflexión. Saca otra carta.",    
        "ordinal":2   
    },
    {
        "nombre":"La Emperatriz",
        "palo":"Arcanos Mayores",
        "valor":3,
        "rasgos_enderezada":"Creatividad · Fertilidad · Abundancia · Hedonismo · Energía de lo nuevo",
        "rasgos_girada":"Bloqueo creativo · Rutina · Descontento · Necesidad de estar a solas · Falta de empuje",
        "pasado_enderezada":"Una oportunidad del pasado te seguirá al presente. Algo que comenzaste tiempo atrás puede materializarse, pero sólo a través de cuidado y esfuerzo constante.",
        "pasado_girada":"Una buena oportunidad se ha quedado atrás por falta de empeño, energía o por no llenarte.",
        "presente_enderezada":"Algo nuevo e ilusionante empieza para tí. Tus acciones y tu dedicación serán decisivas. Alguien querido necesita de tu ayuda y se te empuja a ayudarle.",
        "presente_girada":"Calma chicha. Es un momento para reflexionar y tomar aliento. Ojo con estancarse, acostumbrarse o permitir que se nos suban a las barbas.",
        "futuro_enderezada":"Si se cuidan, nuestros planes darán frutos. Es posible que aparezcan nuevas y mejores alternativas. Los cambios serán a mejor. Entre nuevo y viejo, escoge nuevo.",
        "futuro_girada":"Demasiado ruido y carga sobre nosotros. No deberemos cargar con errores ajenos. Necesidad de distanciarse de lo material.",
        "si_no_enderezada":"Buen camino y empuje. SI",
        "si_no_girada":"Cautela, necesidad de amparo. NO.",  
        "ordinal":3      
    },
    {
        "nombre":"El Emperador",
        "palo":"Arcanos Mayores",
        "valor":4,
        "rasgos_enderezada":"Autoridad · Organización · Estabilidad · Protección · Razonamiento y lógica",
        "rasgos_girada":"Descontrol · Falta de estructura · Inseguridad · Abuso de poder · Impulsividad",
        "pasado_enderezada":"En el pasado has sido capaz de ejercer el control sobre tu vida y establecer una base sólida para tus objetivos futuros.",
        "pasado_girada":"En el pasado has tenido dificultades para mantener el control o la estabilidad en tu vida. Este periódo de caos e incertidumbre te ha permitido aprender, crecer y mejorar en lo personal.",
        "presente_enderezada":"Estás en un momento de tu vida en el que estás ejerciendo tu poder y liderazgo de manera efectiva, y estás estableciendo una base sólida para tus objetivos futuros.",
        "presente_girada":"Puede haber desafíos en tu vida que están afectando tu capacidad para liderar efectivamente y establecer una base sólida para tus objetivos futuros. Es posible que necesites trabajar en tu capacidad para adaptarte al cambio y tomar decisiones más flexibles y equilibradas para superar estos desafíos.",
        "futuro_enderezada":"Estás en un camino hacia el éxito y la estabilidad, y estás trabajando arduamente para asegurar tu futuro y establecer una base sólida para tus objetivos futuros.",
        "futuro_girada":"Pueden aparecer desafíos en tu camino hacia el éxito y la estabilidad, y es posible que necesites trabajar en tu capacidad para adaptarte al cambio, tomar decisiones más flexibles y equilibradas, y establecer límites saludables en tus relaciones personales para superar estos desafíos.",
        "si_no_enderezada":"Estás preparado para enfrentar los desafíos que se presenten. SI",
        "si_no_girada":"Falta de control o imposibilidad. NO.",    
        "ordinal":4    
    },
    {
        "nombre":"El Hierofante",
        "palo": "Arcanos Mayores",
        "valor":5,
        "rasgos_enderezada":"Sabiduría y enseñanza · Espiritualidad · Autoridad (benevolente) · Tradición y conformidad · Aprobación social",
        "rasgos_girada":"Rebeldía · Falta de rumbo · Desconexión espiritual · Rechazo de lo impuesto · Necesidad de novedad",
        "pasado_enderezada":"Has trabajado duro para mantener tus valores y creencias a lo largo del tiempo, y has logrado encontrar un equilibrio y una armonía en tu vida.",
        "pasado_girada":"Has enfrentado desafíos para encontrar la estabilidad y la seguridad en tu vida, y has tenido dificultades para mantener tus valores y creencias a lo largo del tiempo.",
        "presente_enderezada":"Estás trabajando para encontrar una mayor armonía y equilibrio en tu vida, y estás buscando formas de mantener tus valores y creencias a lo largo del tiempo. También puede indicar la necesidad de seguir las normas establecidas y las tradiciones, lo que puede limitar tu capacidad para explorar nuevos caminos y tomar decisiones independientes.",
        "presente_girada":"Estás experimentando una fase de cambio y transición en tu vida, y necesitas encontrar nuevas formas de expresarte y dar significado a tu vida.",
        "futuro_enderezada":"Estás en un camino de crecimiento y evolución personal, y estás en el camino correcto para alcanzar tus objetivos a largo plazo. Puede ser una señal de que estás buscando un mentor o un guía para ayudarte a avanzar.",
        "futuro_girada":"Es posible que necesites tomarte un tiempo para reflexionar y explorar tus valores y creencias centrales. Puede ser útil buscar la ayuda de un mentor o un guía espiritual para encontrar tu camino y avanzar hacia tus metas a largo plazo",
        "si_no_enderezada":"Estás recibiendo orientación o ayuda de una fuente confiable. Si",
        "si_no_girada":"Necesitas guia y consejo externo antes de poder afrontar esto. Por ahora NO.",    
        "ordinal":5    
    },
    {
        "nombre": "Los Enamorados",
        "palo": "Arcanos Mayores",
        "valor": 6,
        "rasgos_enderezada": "Amor verdadero, elección importante, unión, armonía, compromiso",
        "rasgos_girada": "Duda, indecisión, conflicto interno, elección difícil, tentación",
        "pasado_enderezada": "Momentos de amor verdadero y elecciones positivas en el pasado.",
        "pasado_girada": "Elecciones difíciles y momentos de indecisión en el pasado.",
        "presente_enderezada": "Estás enfrentando una elección importante en tu vida, pero el amor verdadero y la armonía te guiarán hacia la decisión correcta.",
        "presente_girada": "Estás luchando con una decisión difícil y sientes conflicto interno. Ten cuidado de no ceder a las tentaciones momentáneas.",
        "futuro_enderezada": "Una elección importante te espera en el futuro cercano, pero si sigues tu corazón y tomas decisiones basadas en el amor verdadero, alcanzarás la armonía y el compromiso.",
        "futuro_girada": "Te enfrentarás a decisiones difíciles en el futuro cercano y es posible que te sientas tentado por opciones que no son las mejores para ti. Asegúrate de sopesar cuidadosamente todas tus opciones antes de decidir.",
        "si_no_enderezada": "Sí, si sigues tu corazón y tomas decisiones basadas en el amor verdadero y la armonía.",
        "si_no_girada": "No, aún no estás listo para tomar la decisión que estás considerando o tal vez hay una elección mejor que no has considerado aún.",
        "ordinal":6
    },
    {
        "nombre": "El Carro",
        "palo": "Arcanos Mayores",
        "valor": 7,
        "rasgos_enderezada": "Voluntad, determinación, éxito, control",
        "rasgos_girada": "Falta de dirección, falta de control, obstáculos, fracaso",
        "pasado_enderezada": "Logros pasados, éxitos en el pasado, tomar el control de la situación",
        "pasado_girada": "Fracasos pasados, falta de control en el pasado, falta de dirección",
        "presente_enderezada": "Tomando el control de la situación actual, éxito en el presente, dirección clara",
        "presente_girada": "Falta de control en el presente, falta de dirección, obstáculos en el camino",
        "futuro_enderezada": "Éxito futuro, dirección clara, logro de metas",
        "futuro_girada": "Fracaso futuro, falta de dirección, obstáculos en el camino",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":7
      },
      {
        "nombre": "La Fuerza",
        "palo": "Arcanos Mayores",
        "valor": 8,
        "rasgos_enderezada": "Fortaleza, coraje, dominio propio, autocontrol, confianza en sí mismo",
        "rasgos_girada": "Falta de control, debilidad, falta de autoconfianza, inseguridad, falta de voluntad",
        "pasado_enderezada": "Superación de obstáculos, demostración de fuerza, logro de metas importantes",
        "pasado_girada": "Incapacidad para superar obstáculos, falta de voluntad para alcanzar metas, falta de confianza en uno mismo",
        "presente_enderezada": "Capacidad para afrontar desafíos con fortaleza y coraje, autocontrol, confianza en sí mismo",
        "presente_girada": "Falta de coraje para afrontar desafíos, falta de autocontrol, inseguridad, miedo",
        "futuro_enderezada": "Superación de desafíos, logro de metas importantes, demostración de coraje y fortaleza",
        "futuro_girada": "Falta de capacidad para afrontar desafíos, fracaso en lograr metas importantes, falta de coraje y fortaleza",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":8
    },
    {
        "nombre": "El Ermitaño",
        "palo": "Arcanos mayores",
        "valor": 9,
        "rasgos_enderezada": "Sabiduría, soledad, búsqueda interna, introspección, guía interior.",
        "rasgos_girada": "Soledad forzada, aislamiento, negación de la sabiduría interior, aislamiento excesivo, desconexión de la realidad.",
        "pasado_enderezada": "Un período de reflexión personal, un viaje introspectivo, sabiduría adquirida a través de la experiencia.",
        "pasado_girada": "Un período de soledad dolorosa, una desconexión emocional, falta de dirección en la vida.",
        "presente_enderezada": "Estás en un período de búsqueda interna y reflexión, conectándote con tu sabiduría interior y tomando decisiones basadas en ella.",
        "presente_girada": "Te sientes solo y aislado, incapaz de encontrar la orientación adecuada en la vida, desconectado de tus valores internos.",
        "futuro_enderezada": "Necesitarás buscar respuestas internas y sabiduría para tomar decisiones importantes en el futuro. Confía en tus propios instintos y guía interior.",
        "futuro_girada": "Tendrás dificultades para encontrar el camino correcto en la vida y es posible que te sientas abrumado por la soledad y el aislamiento.",
        "si_no_enderezada": "Esta carta indica la necesidad de tomar un tiempo para la reflexión y buscar la sabiduría interior antes de tomar una decisión importante. La respuesta puede ser sí, siempre y cuando confíes en tu propio juicio.",
        "si_no_girada": "Esta carta puede indicar un período de soledad y desconexión emocional que puede dificultar la toma de decisiones. La respuesta puede ser no, a menos que tomes el tiempo necesario para conectarte contigo mismo y encontrar tu propia guía interna.",
        "ordinal":9
    },
    {
        "nombre": "La Rueda de la Fortuna",
        "palo": "Aracanos Mayores",
        "valor": 10,
        "rasgos_enderezada": "Cambio, evolución, ciclos, destino, movimiento",
        "rasgos_girada": "Cambio negativo, falta de control, obstáculos, destino inevitable",
        "pasado_enderezada": "Período de transición, cambio en la dirección de la vida, buena suerte",
        "pasado_girada": "Período de caos, falta de dirección, mala suerte",
        "presente_enderezada": "Cambio positivo, oportunidades, éxito, buen destino",
        "presente_girada": "Cambio negativo, oportunidades perdidas, obstáculos, mala suerte",
        "futuro_enderezada": "Cambio positivo, evolución, buen destino, suerte",
        "futuro_girada": "Cambio negativo, falta de control, obstáculos, destino inevitable",
        "si_no_enderezada": "Respuesta incierta, pero hay una posibilidad de cambio positivo",
        "si_no_girada": "Respuesta incierta, pero hay una posibilidad de cambio negativo",
        "ordinal":10
    },      
    
    {
        "nombre": "La Justicia",
        "palo": "Arcanos Mayores",
        "valor": 11,
        "rasgos_enderezada": "Verdad, equidad, objetividad, razón, justicia, integridad, equilibrio",
        "rasgos_girada": "Desigualdad, deshonestidad, injusticia, falta de equilibrio, engaño, deshonestidad, falta de integridad",
        "pasado_enderezada": "El consultante pudo haber vivido un evento importante donde se sintió apoyado y comprendido",
        "pasado_girada": "El consultante puede haber tenido un evento donde fue engañado o perjudicado",
        "presente_enderezada": "El consultante está enfrentando un problema legal o situación que requiere de justicia y equidad",
        "presente_girada": "El consultante puede estar viviendo una situación injusta o engañosa, o está siendo deshonesto en sus acciones",
        "futuro_enderezada": "El consultante puede esperar una resolución justa y equitativa a sus problemas, o que se le presentará una oportunidad de ser justo y equitativo",
        "futuro_girada": "El consultante puede esperar una resolución injusta o engañosa a sus problemas, o que necesitará hacer frente a las consecuencias de sus acciones deshonestas",
        "si_no_enderezada": "La respuesta es probablemente sí, siempre y cuando se sigan los procedimientos adecuados y se actúe con integridad",
        "si_no_girada": "La respuesta es probablemente no, ya que puede haber engaño o deshonestidad en la situación actual",
        "ordinal":11
    },
    {
        "nombre": "El Colgado",
        "palo": "Arcanos Mayores",
        "valor": 12,
        "rasgos_enderezada": "Sacrificio, renuncia, perspectiva diferente, liberación",
        "rasgos_girada": "Egoísmo, falta de sacrificio, estancamiento, necesidad de cambio",
        "pasado_enderezada": "Has tenido que hacer sacrificios y renuncias para llegar a donde estás ahora",
        "pasado_girada": "No has estado dispuesto a hacer sacrificios o has tomado malas decisiones que te han llevado a un estancamiento",
        "presente_enderezada": "Estás en un momento de tu vida en el que necesitas hacer sacrificios para lograr tus metas y objetivos",
        "presente_girada": "Estás en un momento en el que necesitas un cambio de perspectiva y dejar de ser egoísta para avanzar",
        "futuro_enderezada": "En el futuro, tendrás que tomar decisiones difíciles y hacer sacrificios para alcanzar tus metas",
        "futuro_girada": "Si no haces cambios importantes en tu vida, te quedarás estancado en el futuro",
        "si_no_enderezada": "La respuesta es sí, pero necesitas estar dispuesto a hacer sacrificios",
        "si_no_girada": "La respuesta es no, pero necesitas cambiar tu perspectiva y dejar de ser egoísta para avanzar",
        "ordinal":12
    },
    {
        "nombre": "La Muerte",
        "palo": "Arcanos Mayores",
        "valor": 13,
        "rasgos_enderezada": "transformación, cambio, fin de ciclos, evolución, renacimiento",
        "rasgos_girada": "resistencia al cambio, miedo al fin, estancamiento, resistencia al crecimiento personal, estancamiento",
        "pasado_enderezada": "una etapa de cambios importantes que llevaron a la persona a un nuevo capítulo en su vida",
        "pasado_girada": "una resistencia a los cambios y miedo a dejar ir lo que ya no sirve, lo que llevó a estancamiento",
        "presente_enderezada": "un momento de cambio importante, una transformación que se está llevando a cabo en la vida de la persona",
        "presente_girada": "una resistencia al cambio y miedo a enfrentar lo que está por venir, lo que lleva a estancamiento",
        "futuro_enderezada": "un cambio importante se avecina, una transformación que llevará a la persona a un nuevo capítulo en su vida",
        "futuro_girada": "una resistencia al cambio y miedo a dejar ir lo que ya no sirve, lo que llevará a estancamiento en el futuro",
        "si_no_enderezada": "La respuesta puede ser sí, pero es importante estar preparado para los cambios y transformaciones que vendrán",
        "si_no_girada": "La respuesta puede ser no debido a la resistencia al cambio y el miedo al fin",
        "ordinal":13
    },
    {
        "nombre": "La Templanza",
        "palo": "Arcanos Mayores",
        "valor": 14,
        "rasgos_enderezada": "Balance, autocontrol, adaptabilidad, paciencia, armonía",
        "rasgos_girada": "Desequilibrio, falta de autocontrol, impaciencia, rigidez",
        "pasado_enderezada": "Has logrado un equilibrio emocional y has sido capaz de adaptarte a las circunstancias",
        "pasado_girada": "Has experimentado desequilibrio emocional y falta de adaptación a las circunstancias",
        "presente_enderezada": "Estás en un momento de armonía y equilibrio, siendo capaz de adaptarte a las situaciones que se presenten",
        "presente_girada": "Puedes estar experimentando desequilibrio emocional y falta de adaptación a las circunstancias actuales",
        "futuro_enderezada": "Te espera un futuro de armonía, equilibrio y paciencia, serás capaz de adaptarte a los cambios que se presenten",
        "futuro_girada": "Deberás prestar atención a posibles desequilibrios emocionales y trabajar en tu capacidad de adaptación a los cambios",
        "si_no_enderezada": "La respuesta es sí, siempre y cuando mantengas un equilibrio emocional y estés dispuesto a adaptarte a las circunstancias",
        "si_no_girada": "La respuesta puede ser no si no logras mantener un equilibrio emocional y adaptarte a las circunstancias",
        "ordinal":14
    },
    {
        "nombre": "El Diablo",
        "palo": "Arcanos mayores",
        "valor": 15,
        "rasgos_enderezada": "Obsesión, deseo, tentación, materialismo, esclavitud",
        "rasgos_girada": "Liberación, superación, romper con lo negativo, enfrentamiento a las adicciones",
        "pasado_enderezada": "Había situaciones que generaban tentación o adicción y se cayó en ellas",
        "pasado_girada": "Fue posible superar situaciones tentadoras o adictivas en el pasado",
        "presente_enderezada": "Hay situaciones que generan tentación o adicción y se está cayendo en ellas",
        "presente_girada": "Es posible liberarse de situaciones tentadoras o adictivas en el presente",
        "futuro_enderezada": "Habrá situaciones que generen tentación o adicción, es necesario estar alerta",
        "futuro_girada": "Será posible superar situaciones tentadoras o adictivas en el futuro",
        "si_no_enderezada": "Respuesta negativa, indica posibilidad de caer en tentaciones o adicciones",
        "si_no_girada": "Respuesta positiva, indica posibilidad de liberación y superación de tentaciones o adicciones",
        "ordinal":15
    },
    {
        "nombre": "La Torre",
        "palo": "Arcanos Mayores",
        "valor": 16,
        "rasgos_enderezada": "Cambio repentino, crisis, destrucción de estructuras inestables.",
        "rasgos_girada": "Evacuación de emergencia, caída de planes, desmoronamiento interno.",
        "pasado_enderezada": "Ha habido un evento dramático que cambió el rumbo de tu vida.",
        "pasado_girada": "Estás tratando de negar o minimizar un evento dramático que cambió el rumbo de tu vida.",
        "presente_enderezada": "Estás pasando por un período de gran cambio y ruptura de estructuras obsoletas.",
        "presente_girada": "Estás tratando de resistir al cambio y aferrarte a estructuras que ya no funcionan.",
        "futuro_enderezada": "Debes estar preparado para grandes cambios y una destrucción de estructuras anticuadas para avanzar en tu camino.",
        "futuro_girada": "Debes estar preparado para grandes cambios, pero estás renunciando a tomar medidas para hacer frente a ellos.",
        "si_no_enderezada": "No, se acerca una gran interrupción en tu vida que necesitas abordar.",
        "si_no_girada": "Sí, estás tratando de evitar un cambio inevitable que necesita suceder.",
        "ordinal":16
    },
    {
        "nombre": "La Estrella",
        "palo": "Arcanos Mayores",
        "valor": 17,
        "rasgos_enderezada": "Esperanza, inspiración, renovación, optimismo, fe.",
        "rasgos_girada": "Desilusión, falta de fe, obstáculos, falta de inspiración, desesperanza.",
        "pasado_enderezada": "Momento de renovación, inspiración y esperanza. Se superaron obstáculos y se recuperó la fe en uno mismo.",
        "pasado_girada": "Momento de desilusión, falta de fe y obstáculos que impidieron avanzar en el camino.",
        "presente_enderezada": "Llegada de una nueva etapa, oportunidades que inspiran y renuevan la esperanza. Sentimiento de optimismo y fe en el futuro.",
        "presente_girada": "Desilusión, obstáculos que impiden avanzar, falta de inspiración y fe en el futuro.",
        "futuro_enderezada": "Superación de obstáculos, inspiración y renovación que permiten alcanzar los objetivos y realizar los sueños. Éxito, optimismo y fe en el futuro.",
        "futuro_girada": "Falta de fe en uno mismo y en el futuro, desilusión y obstáculos que impiden avanzar en el camino hacia los objetivos.",
        "si_no_enderezada": "Sí, es una carta de esperanza y optimismo.",
        "si_no_girada": "No, hay obstáculos y desilusión que impiden avanzar en el camino.",
        "ordinal":17
    },
    {
        "nombre": "La Luna",
        "palo": "Arcanos Mayores",
        "valor": 18,
        "rasgos_enderezada": "Intuición, misterio, ilusión, creatividad, secretos.",
        "rasgos_girada": "Decepción, desilusión, confusión, ansiedad, inseguridad.",
        "pasado_enderezada": "Momentos de incertidumbre y desconcierto en el pasado que ayudaron a desarrollar tu intuición y creatividad.",
        "pasado_girada": "Engaños y decepciones en el pasado que han generado inseguridad y confusión en ti.",
        "presente_enderezada": "Momento de mayor intuición, creatividad y conexión con lo místico. Puedes descubrir secretos ocultos y tomar decisiones acertadas.",
        "presente_girada": "Confusión y engaños en el presente que te impiden tomar decisiones adecuadas y pueden generar ansiedad e inseguridad.",
        "futuro_enderezada": "Descubrimiento de nuevos conocimientos y una mayor conexión con lo místico. Confía en tu intuición y creatividad para tomar decisiones acertadas.",
        "futuro_girada": "Pérdida de confianza en tus propias capacidades y mayor confusión y ansiedad en el futuro.",
        "si_no_enderezada": "Sí, siempre que confíes en tu intuición y creatividad para tomar la decisión correcta.",
        "si_no_girada": "No, hay engaños y confusión que impiden tomar una decisión clara y acertada.",
        "ordinal":18
    },
    {
        "nombre": "El Sol",
        "palo": "Arcanos Mayores",
        "valor": 19,
        "rasgos_enderezada": "Alegría, éxito, realización, optimismo, creatividad, vitalidad",
        "rasgos_girada": "Egocentrismo, arrogancia, falta de dirección, egoísmo, exceso de confianza",
        "pasado_enderezada": "Has experimentado una etapa de alegría y felicidad en tu vida, en la que te has sentido en plenitud",
        "pasado_girada": "Puede que hayas pasado por una etapa de oscuridad y tristeza, y que ahora te cueste ver la luz",
        "presente_enderezada": "El Sol te anuncia éxito, realización y felicidad en el presente. Te sientes con energía, vitalidad y entusiasmo para emprender nuevos proyectos",
        "presente_girada": "En el presente puedes estar pasando por un momento difícil, en el que te cuesta encontrar la felicidad y la motivación",
        "futuro_enderezada": "El Sol indica que en el futuro habrá éxito y realización en tus proyectos. Serás capaz de superar los obstáculos y avanzar con seguridad hacia tus metas",
        "futuro_girada": "Puedes estar pasando por un momento de confusión y desorientación en el que no sabes qué camino tomar.",
        "si_no_enderezada": "Sí, definitivamente",
        "si_no_girada": "Puede que no sea el momento adecuado, necesitas más claridad y energía",
        "ordinal":19
    },
    {
        "nombre": "El Juicio",
        "palo": "Arcanos Mayores",
        "valor": 20,
        "rasgos_enderezada": "Renacimiento, cambio, transformación, realización, liberación",
        "rasgos_girada": "Miedo al cambio, resistencia al cambio, falta de autoevaluación, autocondena, falta de perdón",
        "pasado_enderezada": "Ha llegado a un punto de autoevaluación y ha tomado decisiones importantes para su futuro.",
        "pasado_girada": "Ha evitado cambios importantes en su vida y no ha querido enfrentar sus problemas.",
        "presente_enderezada": "Es un momento de evaluación y análisis de su vida. Es hora de tomar decisiones importantes para avanzar en su vida.",
        "presente_girada": "Puede estar experimentando miedo y resistencia al cambio en su vida, lo que le impide avanzar.",
        "futuro_enderezada": "Experimentará una renovación personal y espiritual. Se producirán cambios importantes y positivos en su vida.",
        "futuro_girada": "Si continúa evitando los cambios importantes, puede experimentar una crisis personal y emocional.",
        "si_no_enderezada": "Sí.",
        "si_no_girada": "No.",
        "ordinal":20
    },
    {
        "nombre": "El Mundo",
        "palo": "Arcanos Mayores",
        "valor": 21,
        "rasgos_enderezada": "Finalización de un ciclo exitoso, plenitud, logro de objetivos, realización, perfección.",
        "rasgos_girada": "Estancamiento, incapacidad para avanzar, falta de logros, objetivos no alcanzados, necesidad de cambio.",
        "pasado_enderezada": "Has completado exitosamente un proyecto o etapa importante en tu vida.",
        "pasado_girada": "Tuviste dificultades para completar un proyecto o etapa importante en el pasado.",
        "presente_enderezada": "Estás experimentando una sensación de logro y plenitud en tu vida, y estás listo para enfrentar nuevos desafíos.",
        "presente_girada": "Te sientes estancado en tu vida actual, incapaz de avanzar o completar proyectos.",
        "futuro_enderezada": "Te espera una época de logros y realización personal, y podrías estar en camino de completar un proyecto importante.",
        "futuro_girada": "Podrías experimentar retrasos en la finalización de un proyecto o metas importantes en el futuro cercano.",
        "si_no_enderezada": "Sí, tus esfuerzos serán coronados con éxito y te espera una época de plenitud y logros.",
        "si_no_girada": "No, es posible que experimentes dificultades para completar proyectos o metas importantes en el futuro cercano.",
        "ordinal":21
    },
    {
        "nombre": "As de Bastos",
        "palo": "Bastos",
        "valor": 1,
        "rasgos_enderezada": "Nuevos comienzos, oportunidades, creatividad, entusiasmo",
        "rasgos_girada": "Falta de dirección, falta de motivación, oportunidades perdidas",
        "pasado_enderezada": "Ha tenido éxito en nuevos proyectos y emprendimientos",
        "pasado_girada": "Ha experimentado dificultades para comenzar o completar nuevos proyectos",
        "presente_enderezada": "Una nueva oportunidad o proyecto creativo está en el horizonte",
        "presente_girada": "Puede estar luchando para encontrar una dirección en su vida o trabajo actual",
        "futuro_enderezada": "Un nuevo proyecto o empresa será exitoso y gratificante",
        "futuro_girada": "Puede experimentar dificultades para comenzar o completar nuevos proyectos en el futuro cercano",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":22
    },
    {
        "nombre": "Dos de Bastos",
        "palo": "Bastos",
        "valor": 2,
        "rasgos_enderezada": "Toma de decisiones, planificación, descubrimiento de nuevas oportunidades",
        "rasgos_girada": "Miedo a tomar decisiones, falta de planificación, dificultades para encontrar nuevas oportunidades",
        "pasado_enderezada": "Toma de decisiones acertadas, planificación efectiva, oportunidades aprovechadas",
        "pasado_girada": "Malas decisiones, falta de planificación, oportunidades perdidas",
        "presente_enderezada": "Consideración de opciones, planificación cuidadosa, preparación para nuevas oportunidades",
        "presente_girada": "Indecisión, falta de planificación, oportunidades perdidas o desaprovechadas",
        "futuro_enderezada": "Toma de decisiones acertadas, éxito en proyectos, descubrimiento de nuevas oportunidades",
        "futuro_girada": "Malas decisiones, fracaso en proyectos, dificultades para encontrar nuevas oportunidades",
        "si_no_enderezada": "Sí",
        "si_no_girada": "Probablemente no",
        "ordinal":23
    },
    {
        "nombre": "Tres de Bastos",
        "palo": "Bastos",
        "valor": 3,
        "rasgos_enderezada": "preparación, visión a largo plazo, exploración",
        "rasgos_girada": "falta de planificación, visión a corto plazo, indecisión",
        "pasado_enderezada": "se tomaron decisiones audaces que resultaron en éxito y progreso",
        "pasado_girada": "hubo oportunidades perdidas o malas decisiones que llevaron a un estancamiento",
        "presente_enderezada": "tienes una visión clara y estás tomando medidas para lograr tus objetivos",
        "presente_girada": "puede haber falta de claridad o enfoque en tus objetivos, posibles retrasos",
        "futuro_enderezada": "lograrás el éxito y el progreso a largo plazo que estás buscando",
        "futuro_girada": "puede haber retrasos o desafíos en el camino hacia el éxito a largo plazo",
        "si_no_enderezada": "sí, siempre y cuando tengas una visión clara y estés preparado para tomar medidas audaces",
        "si_no_girada": "puede haber demasiada indecisión o falta de enfoque para lograr el éxito que estás buscando",
        "ordinal":24
    },
    {
        "nombre": "Cuatro de Bastos",
        "palo": "Bastos",
        "valor": 4,
        "rasgos_enderezada": "Celebración, armonía, prosperidad, uniones felices",
        "rasgos_girada": "Interferencias en la celebración, disputas, rupturas en las uniones, frustración",
        "pasado_enderezada": "Has tenido logros importantes y te has celebrado con la gente que te importa",
        "pasado_girada": "No has logrado alcanzar tus objetivos y te has sentido aislado y frustrado",
        "presente_enderezada": "Estás disfrutando de una etapa de éxito, armonía y prosperidad",
        "presente_girada": "Hay interferencias que impiden tu armonía, puede haber discusiones o conflictos",
        "futuro_enderezada": "Tendrás éxito en lo que te propongas, encontrarás la armonía y la celebración en tu vida",
        "futuro_girada": "Habrá retrasos en tus planes, es posible que debas reorganizar tus proyectos y reevaluar tus metas",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":25
    },
    {
        "nombre": "Cinco de Bastos",
        "palo": "Bastos",
        "valor": 5,
        "rasgos_enderezada": "Conflicto, competencia, rivalidad, lucha",
        "rasgos_girada": "Evitando conflictos, resolución de conflictos, reconciliación",
        "pasado_enderezada": "Competiciones y conflictos recientes",
        "pasado_girada": "Evitación de conflictos recientes o resolución de ellos",
        "presente_enderezada": "Competencia o rivalidad presente",
        "presente_girada": "Evitando conflictos o resolviéndolos en el presente",
        "futuro_enderezada": "Conflictos y competencias futuras",
        "futuro_girada": "Resolución de conflictos futuros",
        "si_no_enderezada": "No, hay competencia o conflicto involucrado",
        "si_no_girada": "Sí, se puede evitar o resolver la competencia o conflicto",
        "ordinal":26
    },
    {
        "nombre": "Seis de Bastos",
        "palo": "Bastos",
        "valor": 6,
        "rasgos_enderezada": "Reconocimiento, victoria, orgullo, autoconfianza, liderazgo, éxito.",
        "rasgos_girada": "Arrogancia, exceso de confianza, derrota, deshonor, humillación, envidia.",
        "pasado_enderezada": "Has tenido éxito en un proyecto o tarea y te han reconocido por ello. Has ganado la confianza de los demás y has demostrado tus habilidades y liderazgo.",
        "pasado_girada": "Has sufrido una derrota o humillación pública que ha afectado a tu autoconfianza y reputación. Quizás te hayas excedido en tu confianza o hayas subestimado a tus oponentes.",
        "presente_enderezada": "Estás en una posición de liderazgo y éxito. Has ganado el reconocimiento y la admiración de los demás. Tu autoconfianza está en su punto más alto y estás listo para enfrentar nuevos desafíos.",
        "presente_girada": "Puedes estar luchando por el reconocimiento o el éxito. Puedes sentirte envidioso de los demás o tener una autoconfianza exagerada que te está llevando a tomar malas decisiones.",
        "futuro_enderezada": "Tendrás éxito en tus proyectos y serás reconocido por tus habilidades y liderazgo. Tu autoconfianza y orgullo estarán en su punto más alto.",
        "futuro_girada": "Puedes enfrentar una derrota o humillación pública que afectará a tu autoconfianza y reputación. Deberás ser prudente en tus decisiones y evitar el exceso de confianza.",
        "si_no_enderezada": "Sí, es una carta de éxito y reconocimiento.",
        "si_no_girada": "No, puedes estar enfrentando una derrota o humillación pública que afectará a tu autoconfianza y reputación.",
        "ordinal":27
    },
    {
        "nombre": "Siete de bastos",
        "palo": "Bastos",
        "valor": 7,
        "rasgos_enderezada": "Defensa, lucha por la posición, coraje, determinación, perseverancia.",
        "rasgos_girada": "Defensa inadecuada, sentimiento de desesperación, desgaste emocional, desánimo.",
        "pasado_enderezada": "Has tenido que luchar por tus objetivos y has demostrado coraje y determinación. Eso te ha llevado a una posición privilegiada.",
        "pasado_girada": "Te has sentido desesperado y has perdido la confianza en ti mismo en situaciones difíciles.",
        "presente_enderezada": "Estás defendiendo tus intereses con valentía y determinación. Estás listo para luchar y enfrentarte a los desafíos que se te presenten.",
        "presente_girada": "Estás luchando por tus objetivos, pero te estás sintiendo desanimado y con falta de energía. Puedes estar experimentando una defensa inadecuada.",
        "futuro_enderezada": "Tendrás que defender tus intereses y posición con determinación y perseverancia. Si mantienes la fortaleza, lograrás tus objetivos.",
        "futuro_girada": "Puede que tengas dificultades para defender tus intereses y que experimentes una sensación de desesperación y pérdida de confianza en ti mismo. Necesitarás buscar apoyo y encontrar una manera de recuperar la confianza en ti mismo.",
        "si_no_enderezada": "Sí, debes luchar y defender tus intereses.",
        "si_no_girada": "Puede que necesites replantear tu estrategia y encontrar una nueva manera de defender tus intereses.",
        "ordinal":28
    },
    {
        "nombre": "Ocho de Bastos",
        "palo": "Bastos",
        "valor": 8,
        "rasgos_enderezada": "Movimiento rápido, acción, progreso, viajes, noticias inesperadas",
        "rasgos_girada": "Retraso, obstáculos, falta de progreso, comunicaciones perdidas o retrasadas",
        "pasado_enderezada": "Período de acción rápida y progreso, logro de metas, noticias positivas",
        "pasado_girada": "Falta de progreso, retrasos o dificultades para lograr metas, comunicaciones perdidas o retrasadas",
        "presente_enderezada": "Acción rápida, progreso, noticias inesperadas, viajes",
        "presente_girada": "Retrasos, obstáculos, falta de progreso, comunicaciones perdidas o retrasadas",
        "futuro_enderezada": "Acción rápida y progreso, éxito en proyectos y metas, noticias inesperadas",
        "futuro_girada": "Falta de progreso, retrasos o dificultades para lograr metas, comunicaciones perdidas o retrasadas",
        "si_no_enderezada": "Sí",
        "si_no_girada": "Probablemente sí",
        "ordinal":29
    },
    {
        "nombre": "Nueve de Bastos",
        "palo": "Bastos",
        "valor": 9,
        "rasgos_enderezada": "Resistencia, perseverancia, defensa",
        "rasgos_girada": "Agotamiento, rendición, ser vencido",
        "pasado_enderezada": "Superaste obstáculos y te hiciste más fuerte",
        "pasado_girada": "Experiencias pasadas han dejado una marca profunda",
        "presente_enderezada": "Enfrentando desafíos con valentía y determinación",
        "presente_girada": "Te sientes abrumado y agotado por las demandas de la vida",
        "futuro_enderezada": "Lograrás superar los obstáculos y alcanzar tus metas",
        "futuro_girada": "La adversidad seguirá obstaculizando tu camino hacia el éxito",
        "si_no_enderezada": "Sí, si estás dispuesto a trabajar duro y afrontar los desafíos",
        "si_no_girada": "No, estás demasiado cansado o desmotivado para enfrentar los desafíos",
        "ordinal":30
    },
    {
        "nombre": "Diez de Bastos",
        "palo": "Bastos",
        "valor": 10,
        "rasgos_enderezada": "Carga pesada, responsabilidades, esfuerzo, trabajo duro.",
        "rasgos_girada": "Exceso de carga, abrumado, falta de energía, agotamiento.",
        "pasado_enderezada": "Período de mucho trabajo y esfuerzo, superación de obstáculos.",
        "pasado_girada": "Situaciones de mucho estrés y presión, agotamiento físico y mental.",
        "presente_enderezada": "Está logrando mucho, aunque se siente cansado, está cerca de completar un proyecto o una tarea importante.",
        "presente_girada": "Siente que no puede más, se siente abrumado por las responsabilidades y no encuentra la fuerza para seguir adelante.",
        "futuro_enderezada": "Se vislumbra una etapa de finalización de proyectos y éxito, aunque todavía tendrá que esforzarse para lograrlo.",
        "futuro_girada": "Puede haber retrasos en la finalización de proyectos debido a la sobrecarga de trabajo y responsabilidades, pueden aparecer problemas de salud debido al estrés y el agotamiento.",
        "si_no_enderezada": "Sí, pero con mucho esfuerzo y dedicación.",
        "si_no_girada": "No, no hay fuerzas suficientes para lograr lo que se busca.",
        "ordinal":31
    },
    {
        "nombre": "Sota de Bastos",
        "palo": "Bastos",
        "valor": 11,
        "rasgos_enderezada": "Persona joven, apasionada y enérgica. Es una líder natural, valiente y decidida. Está dispuesta a asumir riesgos y a luchar por lo que quiere. Tiene ideas creativas y una gran determinación para llevarlas a cabo.",
        "rasgos_girada": "Puede representar a una persona inmadura o irresponsable, que se deja llevar por sus impulsos y no piensa en las consecuencias de sus acciones. Puede ser arrogante y conflictiva, y tender a imponer sus ideas a los demás sin escuchar sus opiniones.",
        "pasado_enderezada": "Has sido valiente y decidido en el pasado, y has asumido riesgos para alcanzar tus metas. Tus ideas creativas te han llevado a lograr éxitos, y has sido una líder natural para los demás.",
        "pasado_girada": "En el pasado, puede que hayas sido impulsivo e irresponsable en algunas decisiones. Puede que hayas causado conflictos con otros por imponer tus ideas sin escuchar sus opiniones.",
        "presente_enderezada": "Estás en una posición de liderazgo y tienes la energía y la determinación para llevar a cabo tus planes. Tienes ideas creativas y la capacidad de motivar a los demás para que te sigan. Es un buen momento para asumir riesgos y luchar por lo que quieres.",
        "presente_girada": "En el presente, puedes estar actuando de forma impulsiva e irresponsable. Puede que tengas conflictos con los demás debido a tu arrogancia o falta de escucha. Es importante que pienses en las consecuencias de tus acciones antes de actuar.",
        "futuro_enderezada": "En el futuro, tendrás éxito en tus planes gracias a tu valentía y determinación. Tu liderazgo natural te permitirá motivar a los demás para que te sigan en tus proyectos. Es un buen momento para asumir riesgos y luchar por lo que quieres.",
        "futuro_girada": "Si no cambias tu actitud, puedes tener problemas en el futuro. Tu arrogancia y falta de escucha pueden causarte conflictos con los demás y hacerte fracasar en tus planes. Es importante que trabajes en mejorar tu relación con los demás y en escuchar sus opiniones.",
        "si_no_enderezada": "Sí, siempre y cuando estés dispuesto a asumir riesgos y luchar por lo que quieres. Si tienes ideas creativas y la determinación para llevarlas a cabo, tendrás éxito.",
        "si_no_girada": "No, a menos que cambies tu actitud. Si sigues siendo impulsivo, arrogante y no escuchas las opiniones de los demás, puedes fracasar en tus planes y tener conflictos con los demás.",
        "ordinal":32
    },
    {
        "nombre": "Caballero de Bastos",
        "palo": "Bastos",
        "valor": 12,
        "rasgos_enderezada": "Ambicioso, dinámico, entusiasta, seguro de sí mismo, emprendedor",
        "rasgos_girada": "Impulsivo, arrogante, malhumorado, imprudente, temerario",
        "pasado_enderezada": "Logró sus objetivos gracias a su determinación y energía. Empezó nuevos proyectos con pasión.",
        "pasado_girada": "Tomó decisiones imprudentes que lo llevaron a fracasos. Tuvo problemas de temperamento.",
        "presente_enderezada": "Está dispuesto a tomar riesgos y a luchar por sus objetivos. Es un líder natural y carismático.",
        "presente_girada": "Es impulsivo y tiene problemas para controlar su temperamento. Puede estar tomando decisiones imprudentes.",
        "futuro_enderezada": "Alcanzará el éxito gracias a su determinación y energía. Se le presentarán nuevas oportunidades para emprender.",
        "futuro_girada": "Tendrá problemas para mantener la calma y la paciencia, lo que puede llevarlo al fracaso. Necesita trabajar en su temperamento.",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":33
    },
    {
        "nombre": "Reina de Bastos",
        "palo": "Bastos",
        "valor": 13,
        "rasgos_enderezada": "Segura, creativa, apasionada, alegre, generosa.",
        "rasgos_girada": "Dominante, egocéntrica, manipuladora, insegura, agresiva.",
        "pasado_enderezada": "Ha sabido enfrentar desafíos con valentía y determinación. Ha tenido éxito en proyectos creativos. Ha sido generosa con su tiempo y recursos.",
        "pasado_girada": "Ha tenido dificultades para establecer límites y ha sido manipulada por otras personas. Ha sido dominante y egocéntrica en sus relaciones.",
        "presente_enderezada": "Está en un momento de gran confianza y seguridad. Se siente inspirada y motivada para perseguir sus objetivos creativos. Está dispuesta a tomar riesgos.",
        "presente_girada": "Puede estar actuando de manera dominante y egocéntrica en sus relaciones. Puede sentirse insegura y necesitar la validación de los demás.",
        "futuro_enderezada": "Tendrá éxito en proyectos creativos y disfrutará de la admiración y el apoyo de los demás. Será un buen momento para tomar riesgos y aventurarse en nuevas direcciones.",
        "futuro_girada": "Puede haber dificultades para establecer límites y relaciones conflictivas con los demás. Puede sentirse insegura y necesitar la validación de los demás para perseguir sus objetivos.",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":34
    },
    {
        "nombre": "Rey de Bastos",
        "palo": "Bastos",
        "valor": 14,
        "rasgos_enderezada": "Hombre moreno, honesto y justo, con gran energía y pasión. Es un líder nato, un hombre de acción y determinación, que inspira a los demás a seguirlo. Tiene una gran fuerza de voluntad y es muy ambicioso. Puede representar a un hombre de negocios, un político o un militar.",
        "rasgos_girada": "Puede representar a un hombre que abusa de su poder y autoridad, que es egoísta y arrogante, y que trata de imponer su voluntad a los demás. También puede indicar falta de energía y motivación, o una persona que no es confiable.",
        "pasado_enderezada": "Has tenido éxito en tus esfuerzos y has alcanzado una posición de liderazgo o autoridad. Has sido ambicioso y determinado, y has logrado tus metas con éxito.",
        "pasado_girada": "Puede indicar que has sido engañado o traicionado por alguien en una posición de autoridad. También puede indicar falta de ambición o motivación en el pasado.",
        "presente_enderezada": "Estás en una posición de liderazgo o autoridad, y tienes una gran energía y pasión por lo que haces. Estás tomando acción para lograr tus metas y estás inspirando a los demás a seguirte.",
        "presente_girada": "Puede indicar una falta de confianza o motivación en el presente. También puede indicar un abuso de poder o autoridad, o una falta de respeto por los demás.",
        "futuro_enderezada": "Tendrás éxito en tus esfuerzos y lograrás tus metas con éxito. Serás un líder fuerte y apasionado, y tendrás un impacto positivo en los demás.",
        "futuro_girada": "Puede indicar una falta de ambición o motivación en el futuro, o que las cosas no saldrán como esperas debido a un abuso de poder o autoridad.",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":35
    },
    {
        "nombre": "As de Copas",
        "palo": "Copas",
        "valor": 1,
        "rasgos_enderezada": "Inspiración, amor, nuevas oportunidades emocionales",
        "rasgos_girada": "Bloqueo emocional, falta de claridad, confusión",
        "pasado_enderezada": "Amor y felicidad en el pasado",
        "pasado_girada": "Dolor emocional, decepción en el pasado",
        "presente_enderezada": "Nuevas oportunidades emocionales y creativas, alegría",
        "presente_girada": "Falta de claridad emocional, bloqueo creativo",
        "futuro_enderezada": "Nuevas oportunidades de amor y felicidad, inspiración creativa",
        "futuro_girada": "Frustración emocional, falta de progreso creativo",
        "si_no_enderezada": "Sí",
        "si_no_girada": "Probablemente no",
        "ordinal":36
    },
    {
        "nombre": "Dos de copas",
        "palo": "Copas",
        "valor": 2,
        "rasgos_enderezada": "Unión, amor, relaciones, armonía, equilibrio emocional.",
        "rasgos_girada": "Desacuerdo, desequilibrio, falta de armonía en las relaciones, problemas emocionales.",
        "pasado_enderezada": "Has experimentado la armonía en tus relaciones o has conocido a alguien que ha significado mucho para ti.",
        "pasado_girada": "Has pasado por una época de desacuerdo y problemas emocionales con alguien cercano.",
        "presente_enderezada": "Estás experimentando un momento de armonía en tus relaciones y unión con los demás.",
        "presente_girada": "Puede haber desacuerdo o falta de armonía en tus relaciones actuales.",
        "futuro_enderezada": "Habrá armonía y equilibrio emocional en tus relaciones futuras.",
        "futuro_girada": "Puede haber problemas o desacuerdos emocionales en tus relaciones futuras.",
        "si_no_enderezada": "La respuesta es sí, hay armonía y equilibrio emocional en tus relaciones actuales o futuras.",
        "si_no_girada": "La respuesta es no, hay desacuerdo o falta de armonía en tus relaciones actuales o futuras.",
        "ordinal":37
    },
    {
        "nombre": "Tres de Copas",
        "palo": "Copas",
        "valor": 3,
        "rasgos_enderezada": "Celebración, alegría, conexión emocional",
        "rasgos_girada": "Soledad, desconección, falta de armonía",
        "pasado_enderezada": "Momentos felices con amigos y seres queridos",
        "pasado_girada": "Problemas en relaciones interpersonales, malentendidos",
        "presente_enderezada": "Celebración y conexión emocional con otros",
        "presente_girada": "Sentimiento de soledad y falta de conexión emocional",
        "futuro_enderezada": "Futuras celebraciones y momentos de felicidad compartida",
        "futuro_girada": "Dificultades para conectar con otros, falta de alegría",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":38
    },    
    {
        "nombre": "Cuatro de Copas",
        "palo": "Copas",
        "valor": 4,
        "rasgos_enderezada": "Meditación, introspección, búsqueda interior",
        "rasgos_girada": "Estancamiento emocional, desapego excesivo",
        "pasado_enderezada": "Período de reflexión y autoanálisis, posibilidad de haber encontrado paz interior",
        "pasado_girada": "Falta de dirección y motivación, decepción o arrepentimiento por oportunidades perdidas",
        "presente_enderezada": "Sensación de insatisfacción con la vida actual, deseo de encontrar nuevas experiencias",
        "presente_girada": "Incapacidad para encontrar satisfacción en la vida actual, tendencia a rechazar nuevas oportunidades",
        "futuro_enderezada": "Nuevas oportunidades que llevan a un mayor crecimiento personal y satisfacción emocional",
        "futuro_girada": "Falta de oportunidades o incapacidad para encontrar satisfacción en el futuro cercano",
        "si_no_enderezada": "Indecisión, necesidad de meditar en la situación antes de tomar una decisión",
        "si_no_girada": "Rechazo a nuevas oportunidades o incapacidad para tomar una decisión clara",
        "ordinal":39
    }, 
    {
        "nombre": "Cinco de Copas",
        "palo": "Copas",
        "valor": 5,
        "rasgos_enderezada": "Pérdida, tristeza, desilusión",
        "rasgos_girada": "Esperanza, recuperación, aceptación",
        "pasado_enderezada": "Ha habido una gran pérdida en tu vida y es posible que todavía estés lidiando con las emociones que conlleva.",
        "pasado_girada": "A pesar de una pérdida significativa en el pasado, has encontrado la manera de seguir adelante y encontrar esperanza en la vida.",
        "presente_enderezada": "Te encuentras en un momento de tristeza o desilusión en tu vida. Puede que te sientas atrapado en el dolor y te cueste avanzar.",
        "presente_girada": "Aunque has pasado por un momento difícil, estás empezando a ver la luz al final del túnel y estás encontrando la manera de seguir adelante.",
        "futuro_enderezada": "Es posible que tengas que pasar por un momento difícil en el futuro cercano. Prepárate para enfrentar las emociones que conlleva y busca apoyo si lo necesitas.",
        "futuro_girada": "Aunque puede haber obstáculos en el camino, estás en un camino hacia la recuperación y la esperanza en el futuro.",
        "si_no_enderezada": "No",
        "si_no_girada": "No te rindas, sigue adelante.",
        "ordinal":40
    },
    {
        "nombre": "Seis de Copas",
        "palo": "Copas",
        "valor": 6,
        "rasgos_enderezada": "Recuerdos felices del pasado, nostalgia, la infancia, regresión",
        "rasgos_girada": "Aferrarse al pasado, dificultad para superar traumas o relaciones pasadas",
        "pasado_enderezada": "Felicidad y alegría en el pasado, buenos recuerdos",
        "pasado_girada": "Aferramiento al pasado, dificultad para dejar ir cosas que ya no están presentes",
        "presente_enderezada": "Recuperación de un viejo amigo, volver a conectar con viejas pasiones",
        "presente_girada": "Dificultad para adaptarse a los cambios, resistencia a los nuevos comienzos",
        "futuro_enderezada": "Recuperación de una vieja amistad, regresar a un lugar importante del pasado",
        "futuro_girada": "Aferrarse al pasado y resistirse al cambio, incapacidad para avanzar",
        "si_no_enderezada": "Sí",
        "si_no_girada": "Sí, pero sólo si dejas ir el pasado",
        "ordinal":41
    },
    {
        "nombre": "Siete de Copas",
        "palo": "Copas",
        "valor": 7,
        "rasgos_enderezada": "imaginación, ilusión, deseo, posibilidades",
        "rasgos_girada": "engaño, desilusión, falsedad, exageración",
        "pasado_enderezada": "momentos felices, ilusiones cumplidas, oportunidades aprovechadas",
        "pasado_girada": "engaño, falsas ilusiones, malas decisiones",
        "presente_enderezada": "posibilidades, imaginación, creatividad, oportunidades que se presentan",
        "presente_girada": "engaños, mentiras, ilusiones que se desvanecen",
        "futuro_enderezada": "ilusiones que se hacen realidad, metas alcanzadas, éxito",
        "futuro_girada": "decepciones, desilusiones, proyectos que se desvanecen",
        "si_no_enderezada": "Sí, siempre y cuando se actúe con objetividad",
        "si_no_girada": "No, hay que tener cuidado con las ilusiones y la falta de objetividad",
        "ordinal":42
    },
    {
        "nombre": "Ocho de Copas",
        "palo": "Copas",
        "valor": 8,
        "rasgos_enderezada": "Partida, moviéndose lejos, cambio de dirección",
        "rasgos_girada": "Miedo al cambio, estancamiento, falta de dirección",
        "pasado_enderezada": "Has dejado atrás algo que ya no te servía, has tomado la decisión de avanzar",
        "pasado_girada": "No has podido avanzar debido a la indecisión, has tenido miedo al cambio",
        "presente_enderezada": "Estás en el proceso de dejar algo atrás y avanzar hacia un nuevo camino",
        "presente_girada": "Te sientes estancado, sin dirección y con miedo al cambio",
        "futuro_enderezada": "Pronto tendrás la oportunidad de dejar algo atrás y avanzar hacia un nuevo camino",
        "futuro_girada": "Puedes estar reteniendo el cambio y las oportunidades de avanzar",
        "si_no_enderezada": "Sí, es hora de dejar atrás algo y avanzar hacia un nuevo camino",
        "si_no_girada": "No, no estás preparado para dejar atrás lo que te retiene",
        "ordinal":43
    },
    {
        "nombre": "Nueve de Copas",
        "palo": "Copas",
        "valor": 9,
        "rasgos_enderezada": "Felicidad, satisfacción, realización, gratificación",
        "rasgos_girada": "Arrogancia, complacencia, exceso",
        "pasado_enderezada": "Logro de metas, realización de deseos, satisfacción emocional",
        "pasado_girada": "Inseguridad, necesidad de validación externa",
        "presente_enderezada": "Plenitud emocional, gratificación, contentamiento",
        "presente_girada": "Exceso, vanidad, falta de satisfacción",
        "futuro_enderezada": "Logro de deseos, éxito emocional, realización personal",
        "futuro_girada": "Falta de satisfacción, complacencia, engaño",
        "si_no_enderezada": "Sí",
        "si_no_girada": "Sí, pero con advertencias",
        "ordinal":44
    },
    {
        "nombre": "Diez de Copas",
        "palo": "Copas",
        "valor": 10,
        "rasgos_enderezada": "Felicidad familiar, amor, armonía, unión, realización emocional",
        "rasgos_girada": "Desunión familiar, ruptura, discordia, falta de realización emocional",
        "pasado_enderezada": "Relaciones familiares positivas, realización emocional, armonía en el hogar",
        "pasado_girada": "Discusiones familiares, falta de realización emocional, desunión",
        "presente_enderezada": "Armonía en las relaciones familiares, realización emocional, amor, felicidad",
        "presente_girada": "Discusiones familiares, falta de realización emocional, desilusión, insatisfacción",
        "futuro_enderezada": "Unión familiar, realización emocional, amor, felicidad",
        "futuro_girada": "Falta de realización emocional, desunión, discordia familiar",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":45
    },
    {
        "nombre": "Sota de Copas",
        "palo": "Copas",
        "valor": 11,
        "rasgos_enderezada": "Sensibilidad, emociones, intuición, creatividad",
        "rasgos_girada": "Inmadurez emocional, influenciabilidad, exceso de emotividad",
        "pasado_enderezada": "Desarrollo de la sensibilidad, inicio de la exploración emocional",
        "pasado_girada": "Inseguridad emocional, falta de madurez emocional",
        "presente_enderezada": "Creatividad, intuición, apertura emocional",
        "presente_girada": "Falta de límites emocionales, inestabilidad",
        "futuro_enderezada": "Desarrollo emocional, crecimiento personal, fortalecimiento de la intuición",
        "futuro_girada": "Inmadurez emocional, exceso de emotividad, falta de límites emocionales",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No definitivo",
        "ordinal":46
    },
    {
        "nombre": "Caballero de Copas",
        "palo": "Copas",
        "valor": 12,
        "rasgos_enderezada": "Sensibilidad, romance, creatividad, compasión",
        "rasgos_girada": "Falta de iniciativa, soñador, manipulador emocional",
        "pasado_enderezada": "Búsqueda del amor y la felicidad, experiencias emocionales intensas",
        "pasado_girada": "Desamor, traición, decepción",
        "presente_enderezada": "Inspiración, apertura emocional, conexión con la creatividad",
        "presente_girada": "Falta de motivación, pasividad, manipulación emocional",
        "futuro_enderezada": "Nuevas oportunidades emocionales, romance, creatividad, sensibilidad",
        "futuro_girada": "Pérdida de la pasión, desmotivación, manipulación emocional",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":47
    },
    {
        "nombre": "Reina de Copas",
        "palo": "Copas",
        "valor": 13,
        "rasgos_enderezada": "Empatía, compasión, ternura, calidez",
        "rasgos_girada": "Manipulación emocional, susceptibilidad excesiva",
        "pasado_enderezada": "Emociones equilibradas, empatía hacia los demás, amor y apoyo",
        "pasado_girada": "Falta de confianza en los demás, incapacidad para expresar emociones",
        "presente_enderezada": "Comprensión y apoyo emocional, equilibrio emocional, serenidad",
        "presente_girada": "Inseguridad emocional, influencia negativa de personas tóxicas",
        "futuro_enderezada": "Amor, apoyo emocional, relaciones profundas y significativas",
        "futuro_girada": "Manipulación emocional, relaciones tóxicas, traición",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":48
    },
    {
        "nombre": "Rey de Copas",
        "palo": "Copas",
        "valor": 14,
        "rasgos_enderezada": "Sensibilidad, compasión, empatía, intuición",
        "rasgos_girada": "Inestabilidad emocional, dependencia, manipulación",
        "pasado_enderezada": "Desarrollo emocional, autoconocimiento, relación amorosa exitosa",
        "pasado_girada": "Desamor, traición, desequilibrio emocional",
        "presente_enderezada": "Apoyo emocional, comprensión, sensibilidad hacia los demás",
        "presente_girada": "Manipulación emocional, indecisión, falta de sinceridad",
        "futuro_enderezada": "Crecimiento emocional, estabilidad, relaciones amorosas armoniosas",
        "futuro_girada": "Desequilibrio emocional, conflictos amorosos, falta de empatía",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":49
    },                                                   
    {
        "nombre": "As de Espadas",
        "palo": "Espadas",
        "valor": 1,
        "rasgos_enderezada": "Claridad mental, toma de decisiones, nuevas ideas, nuevos comienzos, victoria",
        "rasgos_girada": "Confusión mental, indecisión, retrasos, frustración, derrota",
        "pasado_enderezada": "Momento de claridad mental que te permitió tomar decisiones importantes y nuevas ideas que te llevaron al éxito.",
        "pasado_girada": "Confusión mental que te llevó a tomar decisiones equivocadas y a perder oportunidades importantes.",
        "presente_enderezada": "Tienes claridad mental y estás listo para tomar decisiones importantes que te llevarán a la victoria y nuevos comienzos.",
        "presente_girada": "Estás experimentando confusión mental y no estás seguro de qué decisiones tomar, lo que te lleva a retrasos y frustración.",
        "futuro_enderezada": "Tendrás una victoria importante y nuevos comienzos gracias a una decisión importante que tomarás con claridad mental.",
        "futuro_girada": "Experimentarás una derrota importante debido a una decisión equivocada tomada bajo confusión mental.",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":50
    },
    {
        "nombre": "Dos de Espadas",
        "palo": "Espadas",
        "valor": 2,
        "rasgos_enderezada": "Pausa para reflexionar, toma de decisiones, equilibrio",
        "rasgos_girada": "Indecisión, estancamiento, confusión",
        "pasado_enderezada": "Toma de decisiones difíciles, necesidad de buscar un equilibrio",
        "pasado_girada": "Indecisión, falta de acción, estancamiento",
        "presente_enderezada": "Momento de pausa para reflexionar, necesidad de buscar el equilibrio",
        "presente_girada": "Confusión, falta de claridad, bloqueo",
        "futuro_enderezada": "Toma de decisiones importantes, equilibrio y armonía",
        "futuro_girada": "Confusión, estancamiento, falta de acción",
        "si_no_enderezada": "No",
        "si_no_girada": "No, pero aún es posible tomar una decisión",
        "ordinal":51
    },
    {
        "nombre": "Tres de Espadas",
        "palo": "Espadas",
        "valor": 3,
        "rasgos_enderezada": "Dolor, pérdida, traición, separación",
        "rasgos_girada": "Perdón, reconciliación, liberación",
        "pasado_enderezada": "Dolor emocional, traición, pérdida",
        "pasado_girada": "Perdón, liberación, sanación",
        "presente_enderezada": "Dolor emocional, tristeza, desamor",
        "presente_girada": "Perdón, liberación, superación emocional",
        "futuro_enderezada": "Dolor emocional, pérdida, separación",
        "futuro_girada": "Sanación emocional, perdón, reconciliación",
        "si_no_enderezada": "No",
        "si_no_girada": "Sí, pero con dolor emocional",
        "ordinal":52
    },
    {
        "nombre": "Cuatro de Espadas",
        "palo": "Espadas",
        "valor": 4,
        "rasgos_enderezada": "Pausa, descanso, retirada, meditación",
        "rasgos_girada": "Aislamiento, evasión, insomnio",
        "pasado_enderezada": "Tiempo de descanso y recuperación, reflexión sobre la vida y las decisiones",
        "pasado_girada": "Apatía, evitación de problemas y conflictos",
        "presente_enderezada": "Necesidad de descansar y reponer energía, reflexión y meditación para tomar decisiones",
        "presente_girada": "Falta de dirección, falta de sueño o descanso adecuados",
        "futuro_enderezada": "Pausa necesaria para afrontar futuros desafíos, tiempo de reflexión y preparación",
        "futuro_girada": "Dificultad para tomar decisiones, falta de energía y motivación",
        "si_no_enderezada": "No",
        "si_no_girada": "No, pero hay alternativas",
        "ordinal":53
    },
    {
        "nombre": "Cinco de Espadas",
        "palo": "Espadas",
        "valor": 5,
        "rasgos_enderezada": "Desacuerdo, conflicto, engaño, competencia, rivalidad",
        "rasgos_girada": "Perdón, reconciliación, arrepentimiento",
        "pasado_enderezada": "Disputas, traiciones, discusiones, problemas de comunicación",
        "pasado_girada": "Discusiones resueltas, reconciliación, lecciones aprendidas",
        "presente_enderezada": "Conflicto, lucha por el poder, engaño, intriga",
        "presente_girada": "Superación del conflicto, perdón, dejar ir",
        "futuro_enderezada": "Desacuerdo, desilusión, traición, rivalidad",
        "futuro_girada": "Perdón, reconciliación, solución pacífica",
        "si_no_enderezada": "No",
        "si_no_girada": "Sí, pero con concesiones",
        "ordinal":54
    },
    {
        "nombre": "Seis de Espadas",
        "palo": "Espadas",
        "valor": 6,
        "rasgos_enderezada": "Transición, cambio, viaje, recuperación",
        "rasgos_girada": "Estancamiento, resistencia al cambio, dificultad para avanzar",
        "pasado_enderezada": "Período de transición, movimiento hacia una nueva fase, superación de dificultades",
        "pasado_girada": "Estancamiento, dificultades para avanzar, resistencia al cambio",
        "presente_enderezada": "Viaje, movimiento hacia una nueva fase, transición, recuperación",
        "presente_girada": "Retrasos, dificultades para avanzar, resistencia al cambio",
        "futuro_enderezada": "Viaje, transición, movimiento hacia una nueva fase, recuperación",
        "futuro_girada": "Dificultades para avanzar, estancamiento, resistencia al cambio",
        "si_no_enderezada": "Sí, pero con algunas dificultades en el camino",
        "si_no_girada": "No, no es un buen momento para avanzar o hacer cambios importantes",
        "ordinal":55
    },      
    {
        "nombre": "Siete de Espadas",
        "palo": "Espadas",
        "valor": 7,
        "rasgos_enderezada": "Astucia, estrategia, planificación, ingenio",
        "rasgos_girada": "Mentira, traición, engaño, falta de ética",
        "pasado_enderezada": "Éxito a través de la astucia, el ingenio y la estrategia",
        "pasado_girada": "Traición, engaño, pérdida de confianza",
        "presente_enderezada": "El éxito a través de la astucia y la planificación, la superación de obstáculos",
        "presente_girada": "Engaño, falta de ética, necesidad de ser cauteloso",
        "futuro_enderezada": "Triunfo a través de la astucia, la estrategia y la planificación cuidadosa",
        "futuro_girada": "Traición, engaño, falta de honestidad",
        "si_no_enderezada": "No",
        "si_no_girada": "No, pero no se descarta la posibilidad de éxito si se utiliza la astucia",
        "ordinal":56
    },
    {
        "nombre": "Ocho de Espadas",
        "palo": "Espadas",
        "valor": 8,
        "rasgos_enderezada": "Sensación de estar atrapado, limitado o confinado, necesidad de buscar soluciones, explorar opciones",
        "rasgos_girada": "Sentirse liberado, encontrar soluciones, romper con las limitaciones, superar el miedo",
        "pasado_enderezada": "Sentimiento de limitación, necesidad de ser cuidadoso al tomar decisiones, posibles errores de juicio",
        "pasado_girada": "Libertad, liberación de la limitación, superación del miedo, tomar riesgos",
        "presente_enderezada": "Sensación de estar atrapado, limitado o confinado, necesidad de buscar soluciones, explorar opciones",
        "presente_girada": "Sentirse liberado, encontrar soluciones, romper con las limitaciones, superar el miedo",
        "futuro_enderezada": "Posibilidad de encontrar soluciones y escapar de las limitaciones, necesidad de ser valiente y tomar medidas para liberarse",
        "futuro_girada": "Sentimiento de estar atrapado o limitado por un tiempo, necesidad de ser paciente y perseverar para encontrar soluciones",
        "si_no_enderezada": "No",
        "si_no_girada": "Sí",
        "ordinal":57
    },
    {
        "nombre": "Nueve de Espadas",
        "palo": "Espadas",
        "valor": 9,
        "rasgos_enderezada": "Preocupación, ansiedad, miedo, pesadillas",
        "rasgos_girada": "Obsesión, miedo irracional, parálisis",
        "pasado_enderezada": "Dificultades superadas, problemas resueltos, liberación de preocupaciones",
        "pasado_girada": "Traición, crisis emocional, sufrimiento",
        "presente_enderezada": "Ansiedad, inquietud, pesadillas, preocupaciones",
        "presente_girada": "Parálisis, miedo irracional, obsesiones",
        "futuro_enderezada": "Liberación de preocupaciones, superación de problemas, recuperación emocional",
        "futuro_girada": "Miedo y ansiedad persistentes, necesidad de ayuda profesional",
        "si_no_enderezada": "No",
        "si_no_girada": "No, pero no es definitivo",
        "ordinal":58
    },
    {
        "nombre": "Diez de Espadas",
        "palo": "Espadas",
        "valor": 10,
        "rasgos_enderezada": "Finalización, liberación, conclusión de una etapa, transición",
        "rasgos_girada": "Dolor, trauma, sufrimiento, miedo al cambio",
        "pasado_enderezada": "Finalización de una etapa, liberación de una carga, transición hacia un nuevo comienzo",
        "pasado_girada": "Dolor, trauma, sufrimiento, miedo al cambio",
        "presente_enderezada": "Finalización de una etapa, liberación de una carga, preparación para un nuevo comienzo",
        "presente_girada": "Dolor, trauma, sufrimiento, miedo al cambio",
        "futuro_enderezada": "Finalización de una etapa, liberación de una carga, transición hacia un nuevo comienzo",
        "futuro_girada": "Dolor, trauma, sufrimiento, miedo al cambio",
        "si_no_enderezada": "No",
        "si_no_girada": "No, pero es necesario afrontar la situación",
        "ordinal":59
    },
    {
        "nombre": "Sota de Espadas",
        "palo": "Espadas",
        "valor": 11,
        "rasgos_enderezada": "Astucia, inteligencia, pensamiento rápido, juventud",
        "rasgos_girada": "Traición, engaño, manipulación, venganza",
        "pasado_enderezada": "Logros en la educación, éxito en proyectos intelectuales",
        "pasado_girada": "Errores en la toma de decisiones, falta de responsabilidad",
        "presente_enderezada": "Mente clara, perspicacia, sabiduría, capacidad de análisis",
        "presente_girada": "Estrategias engañosas, malas intenciones, traición",
        "futuro_enderezada": "Nuevas ideas, proyectos exitosos, progreso intelectual",
        "futuro_girada": "Problemas de comunicación, engaños, deshonestidad",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":60
    },
    {
        "nombre": "Caballero de Espadas",
        "palo": "Espadas",
        "valor": 12,
        "rasgos_enderezada": "Fuerza, valor, inteligencia, coraje",
        "rasgos_girada": "Agresión, crueldad, falta de compasión",
        "pasado_enderezada": "Superación de obstáculos, triunfo, coraje para enfrentar problemas",
        "pasado_girada": "Conflictos, problemas no resueltos, falta de coraje",
        "presente_enderezada": "Acción decidida, coraje, toma de decisiones valientes",
        "presente_girada": "Acción impulsiva, agresión, falta de reflexión",
        "futuro_enderezada": "Triunfo sobre la adversidad, éxito, coraje para enfrentar nuevos retos",
        "futuro_girada": "Conflictos, obstáculos, falta de coraje para enfrentar retos",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":61
    },
    {
        "nombre": "Reina de Espadas",
        "palo": "Espadas",
        "valor": 13,
        "rasgos_enderezada": "Poder mental, lógica, análisis, perceptividad",
        "rasgos_girada": "Falta de empatía, frialdad, crueldad emocional",
        "pasado_enderezada": "Pensamiento claro y objetivo, toma de decisiones racionales, superación de obstáculos mentales",
        "pasado_girada": "Malas decisiones, acciones impulsivas, falta de perspectiva",
        "presente_enderezada": "Lógica, razón, inteligencia, percepción",
        "presente_girada": "Falta de claridad mental, emociones confusas, pensamiento irracional",
        "futuro_enderezada": "Pensamiento claro y objetivo, resolución de problemas, habilidades analíticas",
        "futuro_girada": "Falta de dirección, confusión, manipulación emocional",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":62
    },
    {
        "nombre": "Rey de Espadas",
        "palo": "Espadas",
        "valor": 14,
        "rasgos_enderezada": "Inteligencia, objetividad, análisis, justicia",
        "rasgos_girada": "Crueldad, malicia, abuso de poder",
        "pasado_enderezada": "Toma de decisiones justas, uso de la razón, liderazgo efectivo",
        "pasado_girada": "Uso abusivo del poder, toma de decisiones crueles, falta de empatía",
        "presente_enderezada": "Pensamiento lógico y racional, enfoque objetivo, justicia",
        "presente_girada": "Crueldad, falta de empatía, abuso de poder",
        "futuro_enderezada": "Uso efectivo de la lógica y la razón, toma de decisiones justas, liderazgo efectivo",
        "futuro_girada": "Abuso de poder, toma de decisiones crueles, falta de empatía",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":63
    },
    {
        "nombre": "As de Oros",
        "palo": "Oros",
        "valor": 1,
        "rasgos_enderezada": "Nuevo comienzo, éxito financiero, estabilidad, prosperidad",
        "rasgos_girada": "Falta de visión a largo plazo, avaricia, pérdida de oportunidades",
        "pasado_enderezada": "Logro de objetivos financieros, éxito en proyectos a largo plazo",
        "pasado_girada": "Pérdida de oportunidades financieras, falta de enfoque en objetivos a largo plazo",
        "presente_enderezada": "Oportunidades financieras, éxito en proyectos a largo plazo, estabilidad",
        "presente_girada": "Pérdida de oportunidades financieras, falta de enfoque en objetivos a largo plazo",
        "futuro_enderezada": "Prosperidad financiera, éxito en proyectos a largo plazo, estabilidad",
        "futuro_girada": "Falta de visión a largo plazo, pérdida de oportunidades financieras, avaricia",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":64
    },
    {
        "nombre": "Dos de Oros",
        "palo": "Oros",
        "valor": 2,
        "rasgos_enderezada": "Equilibrio, adaptabilidad, fluidez, flexibilidad",
        "rasgos_girada": "Desorden, inestabilidad, falta de enfoque",
        "pasado_enderezada": "Búsqueda de equilibrio y estabilidad financiera, habilidad para adaptarse a cambios",
        "pasado_girada": "Falta de estabilidad financiera, incapacidad para adaptarse a cambios",
        "presente_enderezada": "Habilidad para equilibrar varias áreas de la vida, flexibilidad en situaciones de cambio",
        "presente_girada": "Inestabilidad, falta de enfoque en áreas importantes de la vida",
        "futuro_enderezada": "Habilidad para encontrar un equilibrio en situaciones difíciles, adaptabilidad en cualquier situación",
        "futuro_girada": "Desorden, inestabilidad, falta de enfoque en situaciones difíciles",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":65
    },
    {
        "nombre": "Tres de Oros",
        "palo": "Oros",
        "valor": 3,
        "rasgos_enderezada": "Trabajo en equipo, colaboración, realización conjunta",
        "rasgos_girada": "Desacuerdo, falta de cooperación, proyectos que fracasan por falta de colaboración",
        "pasado_enderezada": "Proyectos exitosos que involucraron colaboración y trabajo en equipo",
        "pasado_girada": "Proyectos que fracasaron debido a la falta de colaboración",
        "presente_enderezada": "Trabajo en equipo y colaboración para alcanzar metas y objetivos",
        "presente_girada": "Falta de colaboración y desacuerdo en la dirección de un proyecto",
        "futuro_enderezada": "Colaboración y trabajo en equipo para lograr grandes cosas",
        "futuro_girada": "Proyectos que fracasan debido a la falta de colaboración y coordinación",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":66
    },
    {
        "nombre": "Cuatro de Oros",
        "palo": "Oros",
        "valor": 4,
        "rasgos_enderezada": "Estabilidad financiera, seguridad, bienes materiales, conservación",
        "rasgos_girada": "Avaricia, codicia, aferramiento excesivo a los bienes materiales, miedo a perder lo que se tiene",
        "pasado_enderezada": "Estabilidad financiera, inversión inteligente, ahorro",
        "pasado_girada": "Pérdida de dinero, gastos innecesarios, malas decisiones financieras",
        "presente_enderezada": "Riqueza material, seguridad financiera, comodidad",
        "presente_girada": "Dificultades financieras, pérdida de recursos, avaricia",
        "futuro_enderezada": "Estabilidad financiera a largo plazo, buenos negocios, inversiones sólidas",
        "futuro_girada": "Pérdida de dinero, malas decisiones financieras, avaricia desmesurada",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":67
    },
    {
        "nombre": "Cinco de Oros",
        "palo": "Oros",
        "valor": 5,
        "rasgos_enderezada": "Pérdida, adversidad, dificultad financiera o material, soledad",
        "rasgos_girada": "Superación de la adversidad, ayuda, encuentro de un nuevo camino, oportunidad",
        "pasado_enderezada": "Dificultades económicas, pérdida material, momentos de soledad y desesperanza",
        "pasado_girada": "Superación de las dificultades, apoyo de amigos y familiares, aprendizaje y experiencia",
        "presente_enderezada": "Momentos de adversidad y dificultad económica, falta de recursos y apoyo, sensación de abandono",
        "presente_girada": "Posibilidad de superar las dificultades, ayuda y apoyo de otras personas, nuevas oportunidades y proyectos",
        "futuro_enderezada": "Dificultades financieras y económicas en el futuro, posibles pérdidas y momentos de soledad y desesperanza",
        "futuro_girada": "Superación de las dificultades, ayuda y apoyo de amigos y familiares, nuevos proyectos y oportunidades",
        "si_no_enderezada": "No",
        "si_no_girada": "Sí, pero con dificultades",
        "ordinal":68
    },
    {
        "nombre": "Seis de Oros",
        "palo": "Oros",
        "valor": 6,
        "rasgos_enderezada": "Generosidad, caridad, reciprocidad, equilibrio",
        "rasgos_girada": "Egoísmo, desigualdad, avaricia",
        "pasado_enderezada": "Dar y recibir, equilibrio en las relaciones",
        "pasado_girada": "Falta de reciprocidad, desequilibrio en las relaciones",
        "presente_enderezada": "Generosidad, ayudar a los demás, buena suerte en las finanzas",
        "presente_girada": "Egoísmo, falta de solidaridad, problemas financieros",
        "futuro_enderezada": "Recompensas, prosperidad financiera, reciprocidad en las relaciones",
        "futuro_girada": "Pérdidas financieras, desequilibrio en las relaciones",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":69
    },
    {
        "nombre": "Siete de Oros",
        "palo": "Oros",
        "valor": 7,
        "rasgos_enderezada": "Paciencia, trabajo duro, inversión a largo plazo, perseverancia",
        "rasgos_girada": "Impaciencia, pereza, falta de planificación",
        "pasado_enderezada": "Inversión en proyectos a largo plazo, trabajo duro, dedicación",
        "pasado_girada": "Falta de planificación, impaciencia, falta de compromiso",
        "presente_enderezada": "Evaluación cuidadosa de las opciones, paciencia, trabajo duro",
        "presente_girada": "Falta de compromiso, falta de planificación, falta de esfuerzo",
        "futuro_enderezada": "Inversión a largo plazo, recompensas del trabajo duro, éxito en proyectos futuros",
        "futuro_girada": "Fracaso en proyectos a largo plazo, falta de recompensas, pérdida de paciencia",
        "si_no_enderezada": "Sí, pero requerirá paciencia y trabajo duro",
        "si_no_girada": "No, debido a la falta de planificación y compromiso",
        "ordinal":70
    },
    {
        "nombre": "Ocho de Oros",
        "palo": "Oros",
        "valor": 8,
        "rasgos_enderezada": "Compromiso, dedicación, esfuerzo, aprendizaje",
        "rasgos_girada": "Falta de enfoque, distracción, superficialidad",
        "pasado_enderezada": "Dedicación y esfuerzo en proyectos laborales, avances en habilidades y aprendizaje",
        "pasado_girada": "Falta de enfoque en el trabajo, falta de progreso o reconocimiento",
        "presente_enderezada": "Compromiso y dedicación en proyectos laborales o personales, progreso en habilidades y aprendizaje",
        "presente_girada": "Distracción, falta de enfoque en el trabajo, falta de progreso",
        "futuro_enderezada": "Compromiso y dedicación en el trabajo o en proyectos personales, avances significativos en habilidades y aprendizaje",
        "futuro_girada": "Falta de enfoque, distracción, falta de progreso o éxito",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":71
    },        
    {
        "nombre": "Nueve de Oros",
        "palo": "Oros",
        "valor": 9,
        "rasgos_enderezada": "Independencia financiera, riqueza, seguridad, disfrute de los placeres materiales",
        "rasgos_girada": "Avaricia, falta de generosidad, pérdida de riqueza",
        "pasado_enderezada": "Logro de metas financieras, éxito material, seguridad",
        "pasado_girada": "Malas decisiones financieras, inseguridad, dependencia",
        "presente_enderezada": "Independencia financiera, éxito, seguridad, disfrute de los placeres materiales",
        "presente_girada": "Avaricia, falta de gratitud, pérdida de riqueza",
        "futuro_enderezada": "Riqueza, independencia financiera, éxito material",
        "futuro_girada": "Pérdida financiera, inseguridad, dependencia",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":72
    },
    {
        "nombre": "Diez de Oros",
        "palo": "Oros",
        "valor": 10,
        "rasgos_enderezada": "Riqueza, seguridad financiera, éxito material, estabilidad",
        "rasgos_girada": "Pérdida financiera, codicia, obsesión por el dinero",
        "pasado_enderezada": "Logro financiero, éxito material, estabilidad económica",
        "pasado_girada": "Inseguridad financiera, mala administración del dinero",
        "presente_enderezada": "Seguridad financiera, abundancia, éxito material",
        "presente_girada": "Falta de dinero, inestabilidad financiera, preocupaciones monetarias",
        "futuro_enderezada": "Riqueza, éxito financiero, seguridad económica",
        "futuro_girada": "Pérdida financiera, fracaso económico, inestabilidad monetaria",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":73
    },
    {
        "nombre": "Sota de Oros",
        "palo": "Oros",
        "valor": 11,
        "rasgos_enderezada": "Habilidad, inteligencia, astucia, ambición, concentración",
        "rasgos_girada": "Falta de concentración, pereza, avaricia",
        "pasado_enderezada": "Éxito en los negocios, habilidades prácticas, enfoque en la carrera",
        "pasado_girada": "Fracaso en los negocios, falta de dirección, falta de ambición",
        "presente_enderezada": "Enfoque en la carrera, crecimiento financiero, éxito en los negocios",
        "presente_girada": "Pereza, falta de dirección, desmotivación",
        "futuro_enderezada": "Oportunidades financieras, crecimiento profesional, éxito en los negocios",
        "futuro_girada": "Fracaso financiero, falta de ambición, mala gestión",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":74
    },    
    {
        "nombre": "Caballero de Oros",
        "palo": "Oros",
        "valor": 12,
        "rasgos_enderezada": "Ambición, enfoque, eficiencia, trabajo duro",
        "rasgos_girada": "Avaricia, falta de ética, deshonestidad",
        "pasado_enderezada": "Logro de metas, éxito financiero, enfoque en objetivos",
        "pasado_girada": "Mala gestión financiera, falta de éxito",
        "presente_enderezada": "Enfoque en el trabajo, productividad, éxito financiero",
        "presente_girada": "Desorden financiero, falta de dirección",
        "futuro_enderezada": "Éxito financiero, logro de metas, enfoque en la carrera",
        "futuro_girada": "Pérdida financiera, fracaso profesional",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":75
    },
    {
        "nombre": "Reina de Oros",
        "palo": "Oros",
        "valor": 13,
        "rasgos_enderezada": "Práctica, generosa, cariñosa, fiable",
        "rasgos_girada": "Codicia, dependencia financiera, terquedad",
        "pasado_enderezada": "Uso práctico del dinero, inversión sabia, estabilidad financiera",
        "pasado_girada": "Mala gestión financiera, dependencia económica de otros",
        "presente_enderezada": "Generosidad, estabilidad financiera, prosperidad",
        "presente_girada": "Codicia, avaricia, falta de gratitud",
        "futuro_enderezada": "Estabilidad financiera, prosperidad, seguridad material",
        "futuro_girada": "Pérdida financiera, malas inversiones, inseguridad material",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":76
    },
    {
        "nombre": "Rey de Oros",
        "palo": "Oros",
        "valor": 14,
        "rasgos_enderezada": "Honestidad, generosidad, seguridad financiera, éxito material",
        "rasgos_girada": "Avaricia, arrogancia, materialismo",
        "pasado_enderezada": "Estabilidad financiera, éxito en los negocios, honradez",
        "pasado_girada": "Malos negocios, falta de ética, problemas financieros",
        "presente_enderezada": "Seguridad financiera, éxito material, prosperidad",
        "presente_girada": "Avaricia, falta de ética, exceso de materialismo",
        "futuro_enderezada": "Seguridad financiera a largo plazo, éxito empresarial, estabilidad",
        "futuro_girada": "Pérdida financiera, mala gestión empresarial, falta de ética",
        "si_no_enderezada": "Sí",
        "si_no_girada": "No",
        "ordinal":77
    }         
];

